name: reacon_customer
description: App for customers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:

  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  flutter_bloc: ^7.3.0
  flutter_svg: ^0.23.0+1
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  lint: ^1.5.3
  freezed_annotation: ^0.14.2
  firebase_messaging: ^11.2.4
  flutter_phoenix: ^1.0.0
  country_code_picker: ^2.0.1
  another_flushbar: ^1.10.24
  injectable: ^1.4.1
  flushbar: ^1.10.4
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  dio: ^4.0.4
  flutter_secure_storage: ^4.2.1
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  select_form_field: "^2.2.0"
  syncfusion_flutter_charts: ^19.2.51
  image_picker: ^0.8.3
  im_stepper: ^0.1.3
  flutter_rating_bar: ^4.0.0
  animation_wrappers: ^0.0.4
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  flutter:
    sdk: flutter
  flutter_sound: ^8.3.12
  file_picker: ^4.2.5
  rxdart: ^0.27.3
  cached_network_image: ^3.2.0
  geolocator: ^8.0.1
  geocoding: ^2.0.1
  google_place: ^0.4.7
  google_geocoding: ^0.2.0 
  flutter_geocoder: ^0.2.2-nullsafety
  permission_handler: ^10.0.0
  maps_toolkit: ^2.0.1
  geoflutterfire: ^3.0.1
  url_launcher: ^6.1.5





dev_dependencies:
  build_runner: ^2.0.6

  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/
    - images/footermenu/
    - assets/
    - assets/onboard/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages