part of 'order_bloc.dart';

@freezed
class OrderState with _$OrderState {
  const factory OrderState({
    required OrderModel order,
    required FoodModel food,
    required List<Order> orders,
    required bool loading,
    required List<RouteModel> routes,
    required List<BusModel> buses,
    required RouteModel route,
    required BusModel bus,
    required String busNo,
    required String seatNo,
    required String departure,
    required double originPrice,
    required String address,
    required TravelOrderModel travelOrder,
    required Option<Either<OrderFailure, OrderModel>> order0ption,
    required Option<Either<OrderFailure, TravelOrderModel>> travelOrderOption,
  }) = _OrderState;

  factory OrderState.initial() => OrderState(
        order: OrderModel(
          customer: '',
          phone: '',
          foodName: '',
          price: 0,
          status: '',
          customerLocation: GeoPoint(0, 0),
          id: '',
          uid: '',
          image: '',
          destinationName: '',
          quantity: 0,
          transport: 0,
        ),
        loading: false,
        food: FoodModel(
          category: '',
          price: '',
          description: '',
          image: '',
          quantity: '',
          section: '',
          title: '',
        ),
        orders: [],
        routes: [],
        route: RouteModel(
          name: "",
        ),
        buses: [],
        bus: BusModel(name: ""),
        order0ption: none(),
        originPrice: 0,
        busNo: '',
        seatNo: '',
        departure: '',
        travelOrder: TravelOrderModel(
          customer: '',
          phone: '',
          foodName: '',
          price: 0,
          status: '',
          route: '',
          bus: '',
          busNo: '',
          departureTime: '',
          uid: '',
          id: '',
          quantity: 0,
          image: '',
        ),
        travelOrderOption: none(),
        address: 'Unknown',
      );
}
